export const ordersData = [
  {
    img: './assets/img/products/1.png',
    title: 'Футболка UZcotton мужская',
    color: 'белый',
    size: 56,
    collection: 'WB',
    brend: 'ООО Вайлдберриз',
    quantity: 1,
    curentPrice: 522,
    withoutDiscount: 1051,
    inStock: 3,
    nearestStock: 3,
    date: ['5—6 февраяля', '7—8 февраяля'],
  },
  {
    img: './assets/img/products/2.png',
    title: 'Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe',
    color: 'прозрачный',
    size: '',
    collection: 'WB',
    brend: 'OOO Мегапрофстиль',
    quantity: 200,
    curentPrice: '10500',
    withoutDiscount: '11500',
    inStock: 230,
    nearestStock: 184,
    date: ['5—6 февраяля', '7—8 февраяля'],
  },
  {
    img: './assets/img/products/3.png',
    title: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные,Faber-Castell',
    color: '',
    size: '',
    collection: 'WB',
    brend: 'ООО Вайлдберриз',
    quantity: 2,
    curentPrice: 247,
    withoutDiscount: 475,
    inStock: 4,
    nearestStock: 4,
    date: ['5—6 февраяля', '7—8 февраяля'],
  },
]
