export const ordersData = [
  {
    img: './assets/img/products/1.png',
    title: 'Футболка UZcotton мужская',
    color: 'белый',
    size: 56,
    collection: 'WB',
    brend: 'ООО Вайлдберриз',
    curentPrice: 522,
    discountPrice: 1051,
  },
  {
    img: './assets/img/products/2.png',
    title: 'Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe',
    color: 'прозрачный',
    size: '',
    collection: 'WB',
    brend: 'OOO Мегапрофстиль',
    curentPrice: "2100047",
    discountPrice: "2300047",
  },
  {
    img: './assets/img/products/3.png',
    title: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные,Faber-Castell',
    color: '',
    size: '',
    collection: 'WB',
    brend: 'ООО Вайлдберриз',
    curentPrice: 494,
    discountPrice: 950,
  },
]
